# name: Auto format code via prettier
# run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
# on: [push]
# jobs:
#     Explore-GitHub-Actions:
#         runs-on: ubuntu-latest
#         steps:
#             - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#             - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#             - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#             - name: Check out repository code
#               uses: actions/checkout@v3
#             - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#             - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#             - name: List files in the repository
#               run: |
#                   ls ${{ github.workspace }}
#             - run: echo "ğŸ This job's status is ${{ job.status }}."
# name: Prettier
# run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
# on: [push]

# jobs:
#     build:
#         name: Prettier
#         runs-on: ubuntu-latest
#         steps:
# 		 - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#        - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#        - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#        - name: Check out repository code
#             - uses: actions/checkout@v1
#             - uses: bahmutov/npm-install@v1

#             - run: npm run pretest
#             - run: git status
#             # commit any changed files
#             # https://github.com/mikeal/publish-to-github-action
#             - uses: mikeal/publish-to-github-action@master
#               env:
#                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Continuous Integration

# This action works with pull requests and pushes
on:
    pull_request:
    push:
        branches:
            - main

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}

            - name: Prettify code
              uses: creyD/prettier_action@v4.2
              with:
                  # This part is also where you can pass other options, for example:
                  prettier_options: --write **/*.{js,md}
